# Generated by Django 5.2 on 2025-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=128)),
                ('cantidad', models.IntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('laboratorio', models.CharField(max_length=128)),
            ],
        ),
    ]
