# Generated by Django 5.2 on 2025-09-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(max_length=128)),
                ('otro_contacto', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('razon', models.CharField(max_length=512)),
                ('descripcion', models.TextField(max_length=512)),
                ('profesional', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'historial_clinico',
            },
        ),
        migrations.CreateModel(
            name='ReporteMedico',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=512)),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('profesional', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
            ],
            options={
                'db_table': 'reporte_medico',
            },
        ),
    ]
