# Generated by Django 5.2 on 2025-05-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.TextField(max_length=128)),
                ('nombre', models.TextField(max_length=128)),
                ('apellido', models.TextField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(blank=True, max_length=128, null=True)),
                ('telefono', models.IntegerField()),
                ('otro_contacto', models.IntegerField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('razon', models.TextField(max_length=512)),
                ('nota', models.TextField(max_length=512)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.insumo')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMedico',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=512)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional')),
            ],
        ),
    ]
