# Generated by Django 5.2 on 2025-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='nota',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='razon',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='reportemedico',
            name='descripcion',
            field=models.TextField(max_length=512),
        ),
    ]
