# Generated by Django 5.2 on 2025-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='otro_contacto',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
