# Generated by Django 5.2 on 2025-05-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Paciente', '0002_alter_paciente_otro_contacto'),
        ('Profesional', '0002_alter_disponibilidad_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='insumo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='profesional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional'),
        ),
        migrations.AlterField(
            model_name='reportemedico',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='reportemedico',
            name='profesional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional'),
        ),
    ]
