# Generated by Django 5.2 on 2025-07-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_historialclinico_nota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialclinico',
            old_name='nota',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='razon',
            field=models.CharField(max_length=512),
        ),
    ]
