# Generated by Django 5.2 on 2025-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_alter_historialclinico_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.TextField(max_length=128),
        ),
    ]
