# Generated by Django 5.2 on 2025-05-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='hora',
            field=models.TimeField(),
        ),
    ]
