# Generated by Django 5.2.7 on 2025-11-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_solicitudregistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudregistro',
            old_name='cedula',
            new_name='ci',
        ),
    ]
