# Generated by Django 5.2.7 on 2025-11-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_rename_cedula_solicitudregistro_ci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedAccessToken',
        ),
    ]
