# Generated by Django 5.2 on 2025-05-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_facturacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_total', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('Tarjeta Crédito', 'Trajeta Crédito'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Efectivo', 'Efectivo'), ('Seguro', 'Seguro')], default='Efectivo')),
                ('tipo_facturacion', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente')),
                ('turno', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turno.turno')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('descripción', models.CharField(max_length=512)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('factura', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturacion')),
            ],
        ),
    ]
