# Generated by Django 5.2 on 2025-05-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_facturacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_total', models.IntegerField()),
                ('metodo_pago', models.TextField(max_length=128)),
                ('tipo_facturacion', models.IntegerField()),
                ('estado', models.TextField(max_length=128)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turno.turno')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('descripción', models.TextField(max_length=512)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.facturacion')),
            ],
        ),
    ]
