# Generated by Django 5.2 on 2025-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_alter_detallefactura_factura_alter_facturacion_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta Crédito', 'Trajeta Crédito'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Efectivo', 'Efectivo'), ('Seguro', 'Seguro')], default='Efectivo'),
        ),
    ]
