# Generated by Django 5.2 on 2025-05-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
        ('Paciente', '0001_initial'),
        ('Profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('modalidad', models.TextField(max_length=128)),
                ('estado', models.TextField(max_length=128)),
                ('motivo', models.TextField(max_length=128)),
                ('recordatorio', models.BooleanField()),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional')),
            ],
        ),
    ]
