# Generated by Django 5.2 on 2025-05-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('paciente', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo'), ('Cancelado', 'Cancelado')], default='Activo')),
                ('motivo', models.TextField(max_length=128)),
                ('fue_notificado', models.BooleanField()),
                ('empleado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('profesional', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
            ],
        ),
    ]
