# Generated by Django 5.2.7 on 2025-10-16 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_telefono'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioTurno',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('hora_envio', models.TimeField()),
                ('mensaje', models.TextField(max_length=512)),
                ('enviado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='paciente.paciente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='turno.turno')),
            ],
        ),
    ]
