# Generated by Django 5.2 on 2025-05-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
        ('Paciente', '0003_alter_historialclinico_insumo_and_more'),
        ('Profesional', '0002_alter_disponibilidad_profesional'),
        ('Turno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional'),
        ),
    ]
