# Generated by Django 5.2.7 on 2025-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente'),
        ),
    ]
