# Generated by Django 5.2.8 on 2025-12-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_alter_turno_estado'),
        ('turno', '0002_recordatorioturno'),
    ]

    operations = [
    ]
