# Generated by Django 5.2 on 2025-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0002_alter_turno_empleado_alter_turno_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(),
        ),
    ]
