# Generated by Django 5.2 on 2025-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0003_alter_turno_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='recordatorio',
            new_name='fue_notificado',
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo'), ('Cancelado', 'Cancelado')], default='Activo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial'),
        ),
    ]
