# Generated by Django 5.2 on 2025-05-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=256, null=True)),
                ('telefono', models.CharField(max_length=128)),
                ('especialidad', models.CharField(max_length=256)),
                ('registro_profesional', models.CharField(max_length=256)),
                ('otro_contacto', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('esta_disponible', models.BooleanField(default=True)),
                ('profesional', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
            ],
        ),
    ]
