# Generated by Django 5.2 on 2025-05-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='profesional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional'),
        ),
    ]
