# Generated by Django 5.2 on 2025-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=16),
        ),
    ]
