# Generated by Django 5.2 on 2025-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional', '0002_alter_disponibilidad_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.TextField(max_length=128),
        ),
    ]
