# Generated by Django 5.2 on 2025-05-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('paciente', '0001_initial'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=256)),
                ('descripcion', models.TextField(blank=True, max_length=512, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo')], default='Activo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('mensaje', models.TextField(max_length=512)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('No Enviado', 'No Enviado')], default='Enviado')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('turno', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turno.turno')),
            ],
        ),
    ]
