# Generated by Django 5.2 on 2025-05-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
        ('Turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('titulo', models.TextField(max_length=256)),
                ('descripcion', models.TextField(blank=True, max_length=512, null=True)),
                ('estado', models.TextField(max_length=128)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('mensaje', models.TextField(max_length=512)),
                ('estado', models.TextField(max_length=128)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turno.turno')),
            ],
        ),
    ]
