# Generated by Django 5.2 on 2025-09-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anuncio',
            table='anuncio',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
    ]
