# Generated by Django 5.2 on 2025-05-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunicacion', '0001_initial'),
        ('Paciente', '0002_alter_paciente_otro_contacto'),
        ('Turno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo')], default='Activo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('No Enviado', 'No Enviado')], default='Enviado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='turno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Turno.turno'),
        ),
    ]
