# Generated by Django 5.2 on 2025-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
