# Generated by Django 5.2 on 2025-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('cargo', models.TextField()),
            ],
        ),
    ]
